export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const SET_MOVIE_SUCCESS = 'SET_MOVIE_SUCCESS';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const GET_MOVIE_FORMATS_SUCCESS = 'GET_MOVIE_FORMATS_SUCCESS';

export const DO_SEARCH = 'DO_SEARCH';
export const CHANGE_SHOW_INFO = 'CHANGE_SHOW_INFO';

export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';